### ISSUE TITLE
Infinite loop on the callback

### ISSUE THREAD

**Issue by myaesubi** [michaelschnyder/oidc-angular#3]
Hi Michael @michaelschnyder ,
Thanks a lot for the library you created and it helped me to integrate my SPA app to IdentityServer3; I'm almost there!

I've followed up your sample and with some changes it worked fine on my local. but my SPA app has ng-route configuration and even though the authentication occurs (as checked the logs on both ends), the app goes to an infinite loop in the browsers after the sign-in happens in the IdentityServer3.

e.g. After callback returns, the routing goes to $location.path ('/') which in my route config goes to '/report' route.

Any insight on the configuration or consideration that regards much appreciated.

Thanks,
Mamrez

**Comment by myaesubi** [comment]
It was my bad that $timeout which used for calling the signIn method kept re-running itself, hence closed.

**Comment by michaelschnyder** [comment]
Hi Mamrez, thanks for clarification and sorry for the delay. I hope everything works as expected right now!
